// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"PanPan/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// github第三方回调
				Method:  http.MethodGet,
				Path:    "/github/callback",
				Handler: GithubCallbackHandler(serverCtx),
			},
			{
				// github第三方登陆
				Method:  http.MethodGet,
				Path:    "/github/login",
				Handler: GithubLoginHandler(serverCtx),
			},
			{
				// 用户密码形式登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 用户验证码形式注册/登陆
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				// 发验证码
				Method:  http.MethodPost,
				Path:    "/sendcode",
				Handler: SendcodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					// 用户信息
					Method:  http.MethodPost,
					Path:    "/userinfo",
					Handler: userInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/account"),
	)
}
