version: '3.8'

services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      # 要创建的数据库名称
      # MYSQL_DATABASE: shortener
    volumes:
      #      设置初始化脚本
      - ./script:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"