version: '3.8'

services:
  minio1:
    image: minio/minio
    container_name: minio1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio{1...4}/data --console-address ":9001"
    volumes:
      - ./data/minio1:/data
    networks:
      - minio-net

  minio2:
    image: minio/minio
    container_name: minio2
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio{1...4}/data --console-address ":9001"
    volumes:
      - ./data/minio2:/data
    networks:
      - minio-net

  minio3:
    image: minio/minio
    container_name: minio3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio{1...4}/data --console-address ":9001"
    volumes:
      - ./data/minio3:/data
    networks:
      - minio-net

  minio4:
    image: minio/minio
    container_name: minio4
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio{1...4}/data --console-address ":9001"
    volumes:
      - ./data/minio4:/data
    networks:
      - minio-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./z_minio_cluster/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - minio-net

networks:
  minio-net:    