// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: upload.proto

package server

import (
	"context"

	"PanPan/app/upload/rpc/internal/logic"
	"PanPan/app/upload/rpc/internal/svc"
	"PanPan/app/upload/rpc/types/upload"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	upload.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadServer) UploadFile(ctx context.Context, in *upload.UploadFileReq) (*upload.CommonResp, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *UploadServer) FastUploadFile(ctx context.Context, in *upload.FastUploadFileReq) (*upload.CommonResp, error) {
	l := logic.NewFastUploadFileLogic(ctx, s.svcCtx)
	return l.FastUploadFile(in)
}

func (s *UploadServer) InitialMultipartUpload(ctx context.Context, in *upload.InitialMultipartUploadReq) (*upload.InitialMultipartUploadResp, error) {
	l := logic.NewInitialMultipartUploadLogic(ctx, s.svcCtx)
	return l.InitialMultipartUpload(in)
}

func (s *UploadServer) UploadPart(ctx context.Context, in *upload.UploadPartReq) (*upload.CommonResp, error) {
	l := logic.NewUploadPartLogic(ctx, s.svcCtx)
	return l.UploadPart(in)
}
