// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFileFieldNames          = builder.RawFieldNames(&UserFile{})
	userFileRows                = strings.Join(userFileFieldNames, ",")
	userFileRowsExpectAutoSet   = strings.Join(stringx.Remove(userFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFileRowsWithPlaceHolder = strings.Join(stringx.Remove(userFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	upload_UserFileIdPrefix             = "upload::userFile:id:"
	upload_UserFileUserIdFileSha1Prefix = "upload::userFile:userId:fileSha1:"
)

type (
	userFileModel interface {
		Insert(ctx context.Context, data *UserFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserFile, error)
		FindOneByUserIdFileSha1(ctx context.Context, userId int64, fileSha1 string) (*UserFile, error)
		Update(ctx context.Context, data *UserFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserFileModel struct {
		sqlc.CachedConn
		table string
	}

	UserFile struct {
		Id         int64        `db:"id"`
		UserId     int64        `db:"user_id"`
		FileSha1   string       `db:"file_sha1"` // 文件hash
		FileSize   int64        `db:"file_size"` // 文件大小
		FileName   string       `db:"file_name"` // 文件名
		CreateTime time.Time    `db:"create_time"`
		UpdateTime time.Time    `db:"update_time"`
		DeleteTime sql.NullTime `db:"delete_time"`
		Status     int64        `db:"status"` // 文件状态(0正常1已删除2禁用)
	}
)

func newUserFileModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserFileModel {
	return &defaultUserFileModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_file`",
	}
}

func (m *defaultUserFileModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userFileIdKey := fmt.Sprintf("%s%v", upload_UserFileIdPrefix, id)
	userFileUserIdFileSha1Key := fmt.Sprintf("%s%v:%v", upload_UserFileUserIdFileSha1Prefix, data.UserId, data.FileSha1)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userFileIdKey, userFileUserIdFileSha1Key)
	return err
}

func (m *defaultUserFileModel) FindOne(ctx context.Context, id int64) (*UserFile, error) {
	userFileIdKey := fmt.Sprintf("%s%v", upload_UserFileIdPrefix, id)
	var resp UserFile
	err := m.QueryRowCtx(ctx, &resp, userFileIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFileRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFileModel) FindOneByUserIdFileSha1(ctx context.Context, userId int64, fileSha1 string) (*UserFile, error) {
	userFileUserIdFileSha1Key := fmt.Sprintf("%s%v:%v", upload_UserFileUserIdFileSha1Prefix, userId, fileSha1)
	var resp UserFile
	err := m.QueryRowIndexCtx(ctx, &resp, userFileUserIdFileSha1Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `file_sha1` = ? limit 1", userFileRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, fileSha1); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFileModel) Insert(ctx context.Context, data *UserFile) (sql.Result, error) {
	userFileIdKey := fmt.Sprintf("%s%v", upload_UserFileIdPrefix, data.Id)
	userFileUserIdFileSha1Key := fmt.Sprintf("%s%v:%v", upload_UserFileUserIdFileSha1Prefix, data.UserId, data.FileSha1)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userFileRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FileSha1, data.FileSize, data.FileName, data.DeleteTime, data.Status)
	}, userFileIdKey, userFileUserIdFileSha1Key)
	return ret, err
}

func (m *defaultUserFileModel) Update(ctx context.Context, newData *UserFile) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userFileIdKey := fmt.Sprintf("%s%v", upload_UserFileIdPrefix, data.Id)
	userFileUserIdFileSha1Key := fmt.Sprintf("%s%v:%v", upload_UserFileUserIdFileSha1Prefix, data.UserId, data.FileSha1)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFileRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FileSha1, newData.FileSize, newData.FileName, newData.DeleteTime, newData.Status, newData.Id)
	}, userFileIdKey, userFileUserIdFileSha1Key)
	return err
}

func (m *defaultUserFileModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", upload_UserFileIdPrefix, primary)
}

func (m *defaultUserFileModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFileRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserFileModel) tableName() string {
	return m.table
}
