// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type DownloadCOSReq struct {
	FileSha1 string `json:"fileSha1"`
	FileName string `json:"fileName"`
	FileAddr string `json:"fileAddr"`
}

type DownloadMinioReq struct {
	FileSha1 string `json:"fileSha1"`
	FileName string `json:"fileName"`
	FileAddr string `json:"fileAddr"`
}
