// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package {{.pkg}}
{{.imports}}
{{.vars}}
{{.types}}
{{.new}}
{{.insert}}
{{.find}}
{{.update}}
{{.delete}}
{{.extraMethod}}
{{.tableName}}
