// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"PanPan/app/upload/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					// 秒传文件
					Method:  http.MethodPost,
					Path:    "/fastupload",
					Handler: tryFastFileUploadHandler(serverCtx),
				},
				{
					// 合并分块文件并上传到相应存储
					Method:  http.MethodPost,
					Path:    "/multipartupload/completeuploadpart",
					Handler: CompleteUploadPartHandler(serverCtx),
				},
				{
					// 初始化分块上传文件
					Method:  http.MethodPost,
					Path:    "/multipartupload/init",
					Handler: initialMultipartUploadHandler(serverCtx),
				},
				{
					// 上传分块文件
					Method:  http.MethodPost,
					Path:    "/multipartupload/uploadpart",
					Handler: uploadPartHandler(serverCtx),
				},
				{
					// 上传文件
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: fileUploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file"),
	)
}
